import type { Metadata } from "next";

export const metadata: Metadata = {
   title: "Firsts steps with Next.js",
   description: "Generated by Next.js",
   keywords: [ "Huguez", "info!!!!" ],
 };


export default function AboutPage() {
   return <main>
      About Page
   </main>
}