import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Firsts steps with Next.js",
  description: "Generated by Next.js",
  keywords: [ "About Page", "Huguez", "info!!!!" ],
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode;}>) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
        { children }
      </body>
    </html>
  );
}